### ISSUE TITLE
RDX: Application Launch error on Windows

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4666]
As I am testing the [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/4960066707), I run into this error at launch sometimes.

Steps I ran before I ran into the error.

- Factory Reset
- Launch the App and select `dockerd` as the container engine in the first run dialog

Logs from my machine at this state. Most logs are empty though.

[logs-20230512.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11467915/logs-20230512.zip)

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/59538726/44a73c5b-5457-462b-8919-b1bceaefea98)

**Comment by mook-as** [comment]
From the logs:
```
┌2023-05-12T20:49:13.010Z: Kubernetes was unable to start: c [Error]: C:\Program Files\Rancher Desktop\resources\resources\win32\bin\docker.exe exited with code 1
│    at ChildProcess.<anonymous> (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:8347)
│    at ChildProcess.emit (node:events:527:28)
│    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
│  command: [
│    'C:\\Program Files\\Rancher Desktop\\resources\\resources\\win32\\bin\\docker.exe',
│    'image',
│    'load',
│    '--input',
│    'C:\\Program Files\\Rancher Desktop\\resources\\resources\\rdx-proxy.tgz'
│  ],
│  code: 1,
│  [Symbol(child-process.command)]: 'C:\\Program Files\\Rancher Desktop\\resources\\resources\\win32\\bin\\docker.exe image load --input C:\\Program Files\\Rancher Desktop\\resources\\resources\\rdx-proxy.tgz'
└}                                                                                                                                                                                                                
```

Possibly related:
```
┌2023-05-12T20:49:12.879Z: Launching background process Win32 socket proxy.
│2023-05-12T20:49:12.904Z: Background process Win32 socket proxy exited gracefully.
└2023-05-12T20:49:12.904Z: Not current Win32 socket proxy process; nothing to be done.
```

This is a duplicate of #4551.

**Comment by gunamata** [comment]
I thought this issue has been resolved with https://github.com/rancher-sandbox/rancher-desktop/pull/4583. 
Reopening this as I am running into this too often.

I am testing with this [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/4995665623) at present.

Logs at this state:

[logs-20230516.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11492502/logs-20230516.zip)


![image](https://github.com/rancher-sandbox/rancher-desktop/assets/59538726/93517e11-ae8f-4e85-990d-6b85fd773a92)

**Comment by mook-as** [comment]
The logs are still the same (the background processes are flapping), so this is still a duplicate of #4551.
