### ISSUE TITLE
M3 Max Sonoma 14.1, virtual machine won't start unless Virt Framework selected

### ISSUE THREAD

**Issue by bruno-watt-wcq** [rancher-sandbox/rancher-desktop#5943]
### Actual Behavior

Just upgraded to an M3 Mac, tried installing rancher it seemed fine. But in default setup it hangs. Because of how it hangs you can't actually go and change environment settings and have them apply, you need to go shutdown rancher and restart it.

I selected all of the VirtFramework options, didn't try with individual settings.

I would also note that I have installed 1.11.0 on an m1 Mac with Sonoma 14.1 and it launches in the same config ive been using on it for a while.

### Steps to Reproduce

Install on M3 Mac and try to launch.

### Result

hangs.

### Expected Behavior

launch

### Rancher Desktop Version

1.11.0

### Rancher Desktop K8s Version

1.27.7 and 1.27.6

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Sonoma 14.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
Hard to say what is going on without looking at the logs. Anything interesting in there, or can you upload them?

**Comment by timofey-drozhzhin** [comment]
I just installed Rancher Desktop on a new Macbook Pro M3 Max. I kept on getting connection errors like these
`{"level":"debug","msg":"stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 53224: Connection refused\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 53224: Connection refused\\r\\n\": exit status 255","time":"2023-11-14T17:21:09-06:00"}`

Then came across https://github.com/lima-vm/lima/pull/1951 which talked about enabling VZ by default. Switching Emulation from QEMU to VZ did the trick for me also.

**Comment by timofey-drozhzhin** [comment]
Here's the log from my `lima.ha.stderr.log` when I kept on getting errors.

```
{"error":"exec: \"/opt/socket_vmnet/bin/socket_vmnet\": stat /opt/socket_vmnet/bin/socket_vmnet: no such file or directory","level":"debug","msg":"Failed to look up socket_vmnet path \"/opt/socket_vmnet/bin/socket_vmnet\"","time":"2023-11-14T17:21:09-06:00"}
{"error":"exec: \"socket_vmnet\": executable file not found in $PATH","level":"debug","msg":"Failed to look up socket_vmnet path \"socket_vmnet\"","time":"2023-11-14T17:21:09-06:00"}
{"error":"exec: \"/usr/local/opt/socket_vmnet/bin/socket_vmnet\": stat /usr/local/opt/socket_vmnet/bin/socket_vmnet: no such file or directory","level":"debug","msg":"Failed to look up socket_vmnet path \"/usr/local/opt/socket_vmnet/bin/socket_vmnet\"","time":"2023-11-14T17:21:09-06:00"}
{"error":"exec: \"/opt/homebrew/opt/socket_vmnet/bin/socket_vmnet\": stat /opt/homebrew/opt/socket_vmnet/bin/socket_vmnet: no such file or directory","level":"debug","msg":"Failed to look up socket_vmnet path \"/opt/homebrew/opt/socket_vmnet/bin/socket_vmnet\"","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"Creating iso file /Users/timofey/Library/Application Support/rancher-desktop/lima/0/cidata.iso","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"Using /var/folders/3g/0xwzyylj39vffx_7xss7khfw0000gn/T/diskfs_iso381914058 as workspace","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"Failed to detect CPU features. Assuming that AES acceleration is available on this Apple silicon.","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"OpenSSH version 9.4.1 detected","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com","time":"2023-11-14T17:21:09-06:00"}
{"level":"info","msg":"hostagent socket created at /Users/timofey/Library/Application Support/rancher-desktop/lima/0/ha.sock","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"Start udp DNS listening on: 127.0.0.1:60438","time":"2023-11-14T17:21:09-06:00"}
{"level":"info","msg":"Starting VZ (hint: to watch the boot progress, see \"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/serial*.log\")","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"Start tcp DNS listening on: 127.0.0.1:62829","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"Using search domains: [localdomain]","time":"2023-11-14T17:21:09-06:00"}
{"level":"info","msg":"new connection from  to ","time":"2023-11-14T17:21:09-06:00"}
{"level":"info","msg":"Setting up Rosetta share","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"[VZ] - vm state change: \"VirtualMachineStateStarting\"","time":"2023-11-14T17:21:09-06:00"}
{"level":"info","msg":"[VZ] - vm state change: running","time":"2023-11-14T17:21:09-06:00"}
{"level":"info","msg":"Waiting for the essential requirement 1 of 5: \"ssh\"","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"executing script \"ssh\"","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"executing ssh for script \"ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/bash]","time":"2023-11-14T17:21:09-06:00"}
{"level":"debug","msg":"stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 53224: Connection refused\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 53224: Connection refused\\r\\n\": exit status 255","time":"2023-11-14T17:21:09-06:00"}
{"level":"info","msg":"Waiting for the essential requirement 1 of 5: \"ssh\"","time":"2023-11-14T17:21:19-06:00"}
{"level":"debug","msg":"executing script \"ssh\"","time":"2023-11-14T17:21:19-06:00"}
{"level":"debug","msg":"executing ssh for script \"ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/bash]","time":"2023-11-14T17:21:19-06:00"}
2023/11/14 17:21:21 tcpproxy: for incoming conn 127.0.0.1:62834, error dialing "192.168.5.15:22": connect tcp 192.168.5.15:22: connection was refused
{"level":"debug","msg":"stdout=\"\", stderr=\"kex_exchange_identification: read: Connection reset by peer\\r\\nConnection reset by 127.0.0.1 port 53224\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"kex_exchange_identification: read: Connection reset by peer\\r\\nConnection reset by 127.0.0.1 port 53224\\r\\n\": exit status 255","time":"2023-11-14T17:21:21-06:00"}
{"level":"error","msg":"dhcp: unhandled message type: RELEASE","time":"2023-11-14T17:21:25-06:00"}
{"level":"info","msg":"Waiting for the essential requirement 1 of 5: \"ssh\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing script \"ssh\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for script \"ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/bash]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"stdout=\"\", stderr=\"\", err=\u003cnil\u003e","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"The essential requirement 1 of 5 is satisfied","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"Waiting for the essential requirement 2 of 5: \"user session is ready for ssh\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing script \"user session is ready for ssh\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for script \"user session is ready for ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/bash]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"stdout=\"\", stderr=\"+ timeout 30s bash -c 'until sudo diff -q /run/lima-ssh-ready /mnt/lima-cidata/meta-data 2\u003e/dev/null; do sleep 3; done'\\n\", err=\u003cnil\u003e","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"The essential requirement 2 of 5 is satisfied","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"Waiting for the essential requirement 3 of 5: \"sshfs binary to be installed\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing script \"sshfs binary to be installed\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for script \"sshfs binary to be installed\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/bash]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"stdout=\"/usr/bin/sshfs\\n\", stderr=\"+ timeout 30s bash -c 'until command -v sshfs; do sleep 3; done'\\n\", err=\u003cnil\u003e","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"The essential requirement 3 of 5 is satisfied","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"Waiting for the essential requirement 4 of 5: \"/etc/fuse.conf (/etc/fuse3.conf) to contain \\\"user_allow_other\\\"\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing script \"/etc/fuse.conf (/etc/fuse3.conf) to contain \\\"user_allow_other\\\"\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for script \"/etc/fuse.conf (/etc/fuse3.conf) to contain \\\"user_allow_other\\\"\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/bash]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"stdout=\"\", stderr=\"+ timeout 30s bash -c 'until grep -q ^user_allow_other /etc/fuse*.conf; do sleep 3; done'\\n\", err=\u003cnil\u003e","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"The essential requirement 4 of 5 is satisfied","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"Waiting for the essential requirement 5 of 5: \"the guest agent to be running\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing script \"the guest agent to be running\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for script \"the guest agent to be running\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/bash]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"stdout=\"\", stderr=\"+ sock=/run/lima-guestagent.sock\\n+ timeout 30s bash -c 'until [ -S \\\"/run/lima-guestagent.sock\\\" ]; do sleep 3; done'\\n\", err=\u003cnil\u003e","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"The essential requirement 5 of 5 is satisfied","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"Mounting \"/Users/timofey\" on \"/Users/timofey\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for preparing sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- mkdir -p \"/Users/timofey\"]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"Chosen driver \"openssh-sftp-server\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"Using OpenSSH SFTP Server \"/usr/libexec/sftp-server\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for remote sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- sshfs \":/Users/timofey\" \"/Users/timofey\" -o slave -o allow_other]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"starting sftp server for /Users/timofey","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing OpenSSH SFTP Server: /usr/libexec/sftp-server [/usr/libexec/sftp-server -e -d /Users/timofey]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"waiting for remote ready","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"generated script \"wait-for-remote-ready\" with map map[Dir:/Users/timofey MaxTrial:30]: \"#!/bin/sh\\nset -eu\\ndir=\\\"/Users/timofey\\\"\\nmax_trial=\\\"30\\\"\\nLANG=C\\nLC_ALL=C\\nexport LANG LC_ALL\\ni=0\\nwhile : ; do\\n  # FIXME: not really robust\\n  # spaces in file names are encoded as '\\\\040' in the mount table\\n  if mount | sed 's/\\\\\\\\040/ /g' | grep \\\"on ${dir}\\\" | egrep -qw \\\"fuse.sshfs|osxfuse\\\"; then\\n    echo '{\\\"return\\\":{}}'\\n    exit 0\\n  fi\\n  sleep 1\\n  if [ $i -ge ${max_trial} ]; then\\n    echo \u003e\u00262 \\\"sshfs does not seem to be mounted on ${dir}\\\"\\n    exit 1\\n  fi\\n  i=$((i + 1))\\ndone\\n\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for script \"wait-for-remote-ready\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/sh]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executed script \"wait-for-remote-ready\", stdout=\"{\\\"return\\\":{}}\\n\", stderr=\"\", err=\u003cnil\u003e","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"Mounting \"/tmp/rancher-desktop\" on \"/tmp/rancher-desktop\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for preparing sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- mkdir -p \"/tmp/rancher-desktop\"]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"Chosen driver \"openssh-sftp-server\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"Using OpenSSH SFTP Server \"/usr/libexec/sftp-server\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for remote sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- sshfs \":/tmp/rancher-desktop\" \"/tmp/rancher-desktop\" -o slave -o allow_other]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"starting sftp server for /tmp/rancher-desktop","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing OpenSSH SFTP Server: /usr/libexec/sftp-server [/usr/libexec/sftp-server -e -d /tmp/rancher-desktop]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"waiting for remote ready","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"generated script \"wait-for-remote-ready\" with map map[Dir:/tmp/rancher-desktop MaxTrial:30]: \"#!/bin/sh\\nset -eu\\ndir=\\\"/tmp/rancher-desktop\\\"\\nmax_trial=\\\"30\\\"\\nLANG=C\\nLC_ALL=C\\nexport LANG LC_ALL\\ni=0\\nwhile : ; do\\n  # FIXME: not really robust\\n  # spaces in file names are encoded as '\\\\040' in the mount table\\n  if mount | sed 's/\\\\\\\\040/ /g' | grep \\\"on ${dir}\\\" | egrep -qw \\\"fuse.sshfs|osxfuse\\\"; then\\n    echo '{\\\"return\\\":{}}'\\n    exit 0\\n  fi\\n  sleep 1\\n  if [ $i -ge ${max_trial} ]; then\\n    echo \u003e\u00262 \\\"sshfs does not seem to be mounted on ${dir}\\\"\\n    exit 1\\n  fi\\n  i=$((i + 1))\\ndone\\n\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for script \"wait-for-remote-ready\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/sh]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executed script \"wait-for-remote-ready\", stdout=\"{\\\"return\\\":{}}\\n\", stderr=\"\", err=\u003cnil\u003e","time":"2023-11-14T17:21:31-06:00"}
{"level":"info","msg":"Mounting \"/Volumes\" on \"/Volumes\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for preparing sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- mkdir -p \"/Volumes\"]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"Chosen driver \"openssh-sftp-server\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"Using OpenSSH SFTP Server \"/usr/libexec/sftp-server\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for remote sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- sshfs \":/Volumes\" \"/Volumes\" -o slave -o allow_other]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"starting sftp server for /Volumes","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing OpenSSH SFTP Server: /usr/libexec/sftp-server [/usr/libexec/sftp-server -e -d /Volumes]","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"waiting for remote ready","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"generated script \"wait-for-remote-ready\" with map map[Dir:/Volumes MaxTrial:30]: \"#!/bin/sh\\nset -eu\\ndir=\\\"/Volumes\\\"\\nmax_trial=\\\"30\\\"\\nLANG=C\\nLC_ALL=C\\nexport LANG LC_ALL\\ni=0\\nwhile : ; do\\n  # FIXME: not really robust\\n  # spaces in file names are encoded as '\\\\040' in the mount table\\n  if mount | sed 's/\\\\\\\\040/ /g' | grep \\\"on ${dir}\\\" | egrep -qw \\\"fuse.sshfs|osxfuse\\\"; then\\n    echo '{\\\"return\\\":{}}'\\n    exit 0\\n  fi\\n  sleep 1\\n  if [ $i -ge ${max_trial} ]; then\\n    echo \u003e\u00262 \\\"sshfs does not seem to be mounted on ${dir}\\\"\\n    exit 1\\n  fi\\n  i=$((i + 1))\\ndone\\n\"","time":"2023-11-14T17:21:31-06:00"}
{"level":"debug","msg":"executing ssh for script \"wait-for-remote-ready\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/sh]","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executed script \"wait-for-remote-ready\", stdout=\"{\\\"return\\\":{}}\\n\", stderr=\"\", err=\u003cnil\u003e","time":"2023-11-14T17:21:32-06:00"}
{"level":"info","msg":"Mounting \"/var/folders\" on \"/var/folders\"","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executing ssh for preparing sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- mkdir -p \"/var/folders\"]","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"Chosen driver \"openssh-sftp-server\"","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"Using OpenSSH SFTP Server \"/usr/libexec/sftp-server\"","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executing ssh for remote sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- sshfs \":/var/folders\" \"/var/folders\" -o slave -o allow_other]","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"starting sftp server for /var/folders","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executing OpenSSH SFTP Server: /usr/libexec/sftp-server [/usr/libexec/sftp-server -e -d /var/folders]","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"waiting for remote ready","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"generated script \"wait-for-remote-ready\" with map map[Dir:/var/folders MaxTrial:30]: \"#!/bin/sh\\nset -eu\\ndir=\\\"/var/folders\\\"\\nmax_trial=\\\"30\\\"\\nLANG=C\\nLC_ALL=C\\nexport LANG LC_ALL\\ni=0\\nwhile : ; do\\n  # FIXME: not really robust\\n  # spaces in file names are encoded as '\\\\040' in the mount table\\n  if mount | sed 's/\\\\\\\\040/ /g' | grep \\\"on ${dir}\\\" | egrep -qw \\\"fuse.sshfs|osxfuse\\\"; then\\n    echo '{\\\"return\\\":{}}'\\n    exit 0\\n  fi\\n  sleep 1\\n  if [ $i -ge ${max_trial} ]; then\\n    echo \u003e\u00262 \\\"sshfs does not seem to be mounted on ${dir}\\\"\\n    exit 1\\n  fi\\n  i=$((i + 1))\\ndone\\n\"","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executing ssh for script \"wait-for-remote-ready\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/sh]","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executed script \"wait-for-remote-ready\", stdout=\"{\\\"return\\\":{}}\\n\", stderr=\"\", err=\u003cnil\u003e","time":"2023-11-14T17:21:32-06:00"}
{"level":"info","msg":"Mounting \"/Applications/Rancher Desktop.app/Contents/Resources/resources\" on \"/Applications/Rancher Desktop.app/Contents/Resources/resources\"","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executing ssh for preparing sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- mkdir -p \"/Applications/Rancher Desktop.app/Contents/Resources/resources\"]","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"Chosen driver \"openssh-sftp-server\"","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"Using OpenSSH SFTP Server \"/usr/libexec/sftp-server\"","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executing ssh for remote sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- sshfs \":/Applications/Rancher Desktop.app/Contents/Resources/resources\" \"/Applications/Rancher Desktop.app/Contents/Resources/resources\" -o slave -o allow_other]","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"starting sftp server for /Applications/Rancher Desktop.app/Contents/Resources/resources","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executing OpenSSH SFTP Server: /usr/libexec/sftp-server [/usr/libexec/sftp-server -e -d /Applications/Rancher Desktop.app/Contents/Resources/resources]","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"waiting for remote ready","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"generated script \"wait-for-remote-ready\" with map map[Dir:/Applications/Rancher Desktop.app/Contents/Resources/resources MaxTrial:30]: \"#!/bin/sh\\nset -eu\\ndir=\\\"/Applications/Rancher Desktop.app/Contents/Resources/resources\\\"\\nmax_trial=\\\"30\\\"\\nLANG=C\\nLC_ALL=C\\nexport LANG LC_ALL\\ni=0\\nwhile : ; do\\n  # FIXME: not really robust\\n  # spaces in file names are encoded as '\\\\040' in the mount table\\n  if mount | sed 's/\\\\\\\\040/ /g' | grep \\\"on ${dir}\\\" | egrep -qw \\\"fuse.sshfs|osxfuse\\\"; then\\n    echo '{\\\"return\\\":{}}'\\n    exit 0\\n  fi\\n  sleep 1\\n  if [ $i -ge ${max_trial} ]; then\\n    echo \u003e\u00262 \\\"sshfs does not seem to be mounted on ${dir}\\\"\\n    exit 1\\n  fi\\n  i=$((i + 1))\\ndone\\n\"","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executing ssh for script \"wait-for-remote-ready\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/sh]","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executed script \"wait-for-remote-ready\", stdout=\"{\\\"return\\\":{}}\\n\", stderr=\"\", err=\u003cnil\u003e","time":"2023-11-14T17:21:32-06:00"}
{"level":"info","msg":"Waiting for the final requirement 1 of 1: \"boot scripts must have finished\"","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executing script \"boot scripts must have finished\"","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"Forwarding unix sockets","time":"2023-11-14T17:21:32-06:00"}
{"level":"info","msg":"Forwarding \"/var/run/docker.sock\" (guest) to \"/Users/timofey/.rd/docker.sock\" (host)","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"executing ssh for script \"boot scripts must have finished\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=timofey -o ControlMaster=auto -o ControlPath=\"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 53224 127.0.0.1 -- /bin/bash]","time":"2023-11-14T17:21:32-06:00"}
{"level":"info","msg":"Forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/timofey/Library/Application Support/rancher-desktop/lima/0/ga.sock\" (host)","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"stdout=\"\", stderr=\"+ timeout 30s bash -c 'until sudo diff -q /run/lima-boot-done /mnt/lima-cidata/meta-data 2\u003e/dev/null; do sleep 3; done'\\n\", err=\u003cnil\u003e","time":"2023-11-14T17:21:32-06:00"}
{"level":"info","msg":"The final requirement 1 of 1 is satisfied","time":"2023-11-14T17:21:32-06:00"}
{"level":"debug","msg":"guest agent info: \u0026{LocalPorts:[{IP:0.0.0.0 Port:22} {IP::: Port:22}]}","time":"2023-11-14T17:21:32-06:00"}
```

**Comment by jandubois** [comment]
> @jandubois Here's the log from my `lima.ha.stderr.log` when I kept on getting errors.

I don't understand: that log looks like you are using VZ and it seems to succeed. So it doesn't seem to be from when you were getting errors using QEMU.

**Comment by timofey-drozhzhin** [comment]
@jandubois must be because I copied the log after switching to VZ 🤦‍♂️. I will undo everything and get you the error logs in just a bit.

**Comment by timofey-drozhzhin** [comment]
@jandubois I emailed you a link to all the logs I get during the error, just in case it has any personal information.

Screenshot of the error:
<img width="1286" alt="Screenshot 2023-11-14 at 6 11 15 PM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/26501155/a3577210-0eed-4812-ae7f-99050d761373">

**Comment by jandubois** [comment]
This looks like another instance of https://github.com/lima-vm/lima/issues/1996

From your `serial.log` I can see the error:

```
UEFI firmware (version edk2-stable202302-for-qemu built at 17:14:55 on Mar 15 2023)
Error: Image at 001BFD41000 start failed: Not Found
```

Which looks like an issue in QEMU.

**Comment by joehorsnell** [comment]
> I just installed Rancher Desktop on a new Macbook Pro M3 Max. I kept on getting connection errors like these `{"level":"debug","msg":"stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 53224: Connection refused\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 53224: Connection refused\\r\\n\": exit status 255","time":"2023-11-14T17:21:09-06:00"}`
> 
> Then came across [lima-vm/lima#1951](https://github.com/lima-vm/lima/pull/1951) which talked about enabling VZ by default. I switched the emulation setting from QEMU to VZ (with Rosetta support), and BOOM it worked for me!

For the benefit of other M3 users viewing this issue for help, I also ran into this problem (latest RD version, `1.12.1`) and tried changing the emulation settings to VZ, then applying, but it appeared not to work. The Docker daemon was still not starting.

Digging further I noticed that there were some rogue Rancher Desktop processes still running, even after quitting RD, so for whatever reason the restart process did not work properly (a colleague had exactly the same issue - both same version `1.12.1`). After `kill -9`-ing all the offending processes (`ps -ax | grep -I rancher`) and restarting RD it worked fine with VZ emulation 👍.

**Comment by jandubois** [comment]
You can do the cleanup with a factory reset:

```
/Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/rdctl factory-reset
/Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/rdctl start --experimental.virtual-machine.type vz
```

**Comment by suresharam** [comment]
> > I just installed Rancher Desktop on a new Macbook Pro M3 Max. I kept on getting connection errors like these `{"level":"debug","msg":"stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 53224: Connection refused\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 53224: Connection refused\\r\\n\": exit status 255","time":"2023-11-14T17:21:09-06:00"}`
> > Then came across [lima-vm/lima#1951](https://github.com/lima-vm/lima/pull/1951) which talked about enabling VZ by default. I switched the emulation setting from QEMU to VZ (with Rosetta support), and BOOM it worked for me!
> 
> For the benefit of other M3 users viewing this issue for help, I also ran into this problem (latest RD version, `1.12.1`) and tried changing the emulation settings to VZ, then applying, but it appeared not to work. The Docker daemon was still not starting.
> 
> Digging further I noticed that there were some rogue Rancher Desktop processes still running, even after quitting RD, so for whatever reason the restart process did not work properly (a colleague had exactly the same issue - both same version `1.12.1`). After `kill -9`-ing all the offending processes (`ps -ax | grep -i rancher`) and restarting RD it worked fine with VZ emulation 👍.
> 
> Edit: FYI this was from a clean install on Sonoma 14.2.1, I hadn't previously run RD.

This worked for me on Mac M3, thanks @joehorsnell

**Comment by virtualpeter** [comment]
I wish to report that the issue experienced on M3 chip are also seen with M2-Pro. 

Chip: M2-Pro
macOS: 14.4
RD: 1.12.3
Admin/Sudo: off
Kubernetes: off

Same behaviour I believe. Diagnostics pane says all pass, qemu starts, but ssh atttempts into vm all fail with ec=1 - after a timeout an error dialog appears as reported in #6527  

Switching to VZ works - although a reboot or manual kill of the qemu process is required as mentioned in earlier comments

**Comment by breun** [comment]
@virtualpeter [Rancher Desktop 1.13.0](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.13.0) was released a couple of days ago, which fixed this issue for me on an M3 Pro. I recommend trying that version.

**Comment by virtualpeter** [comment]
> @virtualpeter [Rancher Desktop 1.13.0](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.13.0) was released a couple of days ago, which fixed this issue for me on an M3 Pro. I recommend trying that version.

Can confirm that on M3 device after installing 1.13.0 and doing Factory Reset that it is up and working with qemu. However the M2-Pro device is still failing with qemu at the 'Waiting for the essential requirement 1 of 4: "ssh"' step just as with 1.12.3

**Comment by 87abhii** [comment]
> You can do the cleanup with a factory reset:
> 
> ```
> /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/rdctl factory-reset
> /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/rdctl start --experimental.virtual-machine.type vz
> ```

This works perfectly Thank

**Comment by jandubois** [comment]
This issue has been fixed in 1.13.0

**Comment by kirrg001** [comment]
The CLI arguments were changed meanwhile. Please use:

> $ /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/rdctl factory-reset
> $ /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/rdctl start --virtual-machine.type vz

**Comment by kirrg001** [comment]
@jandubois 

I am still getting the error

> Error Starting Kubernetes
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 255

> Last Command Run
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura shell --workdir=. 0 sudo /bin/sh -c rm -f /usr/local/share/ca-certificates/rd-*.crt

On M4 MAX.

I am on the latest Rancher version. 

I had to use the workaround from [here](https://github.com/rancher-sandbox/rancher-desktop/issues/5943#issuecomment-3155967192).
