### ISSUE TITLE
1.91.1 crashing java apps

### ISSUE THREAD

**Issue by arrrnas** [rancher-sandbox/rancher-desktop#8769]
### Actual Behavior

>In kernel 6.12 some cgroups controllers are removed from v1 and moved to v2.
https://bugs.openjdk.org/browse/JDK-8348566

Apparently this leads to java apps crashing. Docker desktop dealt this this by downgrading the kernel version to v6.10.14: https://github.com/docker/for-mac/issues/7573#issuecomment-2674292418

### Steps to Reproduce

`docker run docker.elastic.co/elasticsearch/elasticsearch:7.16.1`

### Result

```
2025-06-11 09:48:23,462 main ERROR Could not reconfigure JMX java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "anyController" is null
	at java.base/jdk.internal.platform.cgroupv2.CgroupV2Subsystem.getInstance(CgroupV2Subsystem.java:81)
	at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:113)
	at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:167)
	at java.base/jdk.internal.platform.SystemMetrics.instance(SystemMetrics.java:29)
	at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:58)
	at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
	at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:182)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:280)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:199)
	at java.management/java.lang.management.ManagementFactory.lambda$getPlatformMBeanServer$0(ManagementFactory.java:488)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.management/java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:489)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:558)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:207)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:220)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
	at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:251)
	at org.elasticsearch.common.logging.LogConfigurator.configureWithoutConfig(LogConfigurator.java:95)
	at org.elasticsearch.cli.CommandLoggingConfigurator.configureLoggingWithoutConfig(CommandLoggingConfigurator.java:29)
	at org.elasticsearch.cli.Command.main(Command.java:74)
	at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:33)

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "anyController" is null
	at java.base/jdk.internal.platform.cgroupv2.CgroupV2Subsystem.getInstance(CgroupV2Subsystem.java:81)
	at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:113)
	at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:167)
	at java.base/jdk.internal.platform.SystemMetrics.instance(SystemMetrics.java:29)
	at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:58)
	at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
	at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:182)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:280)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:199)
	at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(PlatformMBeanProvider.java:195)
	at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:687)
	at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:389)
	at org.elasticsearch.tools.launchers.DefaultSystemMemoryInfo.<init>(DefaultSystemMemoryInfo.java:29)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:125)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
```

### Expected Behavior

Container runs without crashing

### Rancher Desktop Version

1.19.1

### Rancher Desktop K8s Version

1.30.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

15.4.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
I can reproduce the issue.

I tried to find a workaround, like bind-mounting a "fixed" `cgroups` file over `/proc/cgroups`:

```console
lima-rancher-desktop:/etc# cat /proc/cgroups
#subsys_name	hierarchy	num_cgroups	enabled
cpu	0	7	1
cpuacct	0	7	1
blkio	0	7	1
devices	0	7	1
freezer	0	7	1
net_cls	0	7	1
perf_event	0	7	1
net_prio	0	7	1
hugetlb	0	7	1
pids	0	7	1
lima-rancher-desktop:/etc# mount --bind /etc/cgroups /proc/cgroups
lima-rancher-desktop:/etc# cat /proc/cgroups
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	0	6	1
cpu	0	6	1
cpuacct	0	6	1
blkio	0	6	1
memory	0	6	1
devices	0	6	1
freezer	0	6	1
net_cls	0	6	1
perf_event	0	6	1
net_prio	0	6	1
hugetlb	0	6	1
pids	0	6	1
```

Unfortunately I found no way to bind-mount it into a container; the docker daemon actively blocks it:

```console
❯ docker run -it --rm --privileged -v /etc/cgroups:/proc/cgroups alpine
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/cgroups" to rootfs at "/proc/cgroups": create mountpoint for /proc/cgroups mount: check proc-safety of /proc/cgroups mount: "/var/lib/docker/overlay2/a5135b7729e25376be3c1759dda6db0a5596bd81ed2af522da5fd0e2a087caef/merged/proc/cgroups" cannot be mounted because it is inside /proc: unknown
```

The important bit is right at the end of the error message: `cannot be mounted because it is inside /proc`.

So for now the only "workaround" is to stay with Rancher Desktop 1.18.2. 😦

**Comment by arrrnas** [comment]
Thanks for looking into this, @jandubois. Just so we have an idea of the timeline — do you think the likely solution will be downgrading the kernel version, or waiting for a fix in the kernel and update once it's available?

**Comment by jandubois** [comment]
> do you think the likely solution will be downgrading the kernel version, or waiting for a fix in the kernel and update once it's available?

I don't think there will be a fix in the kernel; it is a bug in OpenJDK, that looks like it has been fixed, but I haven't checked if it has been released.

But that obviously doesn't help with containers using an older version of OpenJDK.

Downgrading the kernel would obviously be a temporary solution; we can't stay on an older kernel indefinitely; but maybe it is necessary for a while to allow all those containers to be rebuilt/updated.

We are currently investigating switching cgroups back from "unified" to "hybrid" mode, to see if that will prevent OpenJDK from misdetecting the cgroups version. I do remember that there was a problem with hybrid mode, but that may also have been just with an older version of OpenRC.

So I can't give you a timeline; for now the options are to use containers built with a fixed version of OpenJDK or staying with Rancher Desktop 1.82.2 until there is a new release that implements a workaround (downgrades kernel, uses hybrid cgroups, or maybe we find another way).

**Comment by mook-as** [comment]
Experimentally re-enabling hybrid cgroups:
```diff
diff --git pkg/rancher-desktop/assets/lima-config.yaml pkg/rancher-desktop/assets/lima-config.yaml
index 0620ce826..b5710b282 100644
--- pkg/rancher-desktop/assets/lima-config.yaml
+++ pkg/rancher-desktop/assets/lima-config.yaml
@@ -48,7 +48,7 @@ provision:
   script: |
     #!/bin/sh
     set -o errexit -o nounset -o xtrace
-    RC_CGROUP_MODE=unified
+    RC_CGROUP_MODE=hybrid
     if ! grep -q -E "^#?rc_cgroup_mode=\"$RC_CGROUP_MODE\"" /etc/rc.conf; then
       sed -i -E "s/^#?rc_cgroup_mode=\".*\"/rc_cgroup_mode=\"$RC_CGROUP_MODE\"/" /etc/rc.conf
       # avoid reboot loop if sed failed for any reason
```

Lets us get past the original point of failure, but still fails:
<details>
<summary>

```
ERROR: [2] bootstrap checks failed. You must address the points described in the following [2] lines before starting Elasticsearch.
bootstrap check failure [1] of [2]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
bootstrap check failure [2] of [2]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/docker-cluster.log
```

</summary>

```
{"type": "server", "timestamp": "2025-06-12T17:16:18,055Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "version[7.16.1], pid[7], build[default/docker/5b38441b16b1ebb16a27c107a4c3865776e20c53/2021-12-11T00:29:38.865893768Z], OS[Linux/6.12.30-1-virt/aarch64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.1/17.0.1+12]" }
{"type": "server", "timestamp": "2025-06-12T17:16:18,058Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]" }
{"type": "server", "timestamp": "2025-06-12T17:16:18,058Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-8752342682551179973, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -Xms2961m, -Xmx2961m, -XX:MaxDirectMemorySize=1552941056, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,521Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [aggs-matrix-stats]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,521Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [analysis-common]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,521Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [constant-keyword]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [frozen-indices]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [ingest-common]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [ingest-geoip]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [ingest-user-agent]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [kibana]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [lang-expression]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [lang-mustache]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [lang-painless]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [legacy-geo]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [mapper-extras]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [mapper-version]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [parent-join]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [percolator]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [rank-eval]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [reindex]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,522Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [repositories-metering-api]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [repository-encrypted]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [repository-url]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [runtime-fields-common]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [search-business-rules]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [searchable-snapshots]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [snapshot-repo-test-kit]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [spatial]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [transform]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [transport-netty4]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [unsigned-long]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [vector-tile]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [vectors]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [wildcard]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-aggregate-metric]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-analytics]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,523Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-async]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,524Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-async-search]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,524Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-autoscaling]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,524Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-ccr]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,524Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-core]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,524Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-data-streams]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,524Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-deprecation]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,524Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-enrich]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,529Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-eql]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,529Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-fleet]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,529Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-graph]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,529Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-identity-provider]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,529Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-ilm]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,530Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-logstash]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,530Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-ml]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,530Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-monitoring]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,530Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-ql]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,530Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-rollup]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,530Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-security]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,530Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-shutdown]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,530Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-sql]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,530Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-stack]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,531Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-text-structure]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,531Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-voting-only-node]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,531Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "loaded module [x-pack-watcher]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,531Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "no plugins loaded" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,556Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "using [1] data paths, mounts [[/ (overlay)]], net usable_space [91.9gb], net total_space [97.8gb], types [overlay]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,556Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "heap size [2.8gb], compressed ordinary object pointers [true]" }
{"type": "server", "timestamp": "2025-06-12T17:16:19,573Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "node name [98f93dc53357], node ID [Ss5QwNv5QPWIXVibiBA-MA], cluster name [docker-cluster], roles [transform, data_frozen, master, remote_cluster_client, data, ml, data_content, data_hot, data_warm, data_cold, ingest]" }
{"type": "server", "timestamp": "2025-06-12T17:16:21,861Z", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "[controller/210] [Main.cc@122] controller (64 bit): Version 7.16.1 (Build 0f7c0c1a01e77a) Copyright (c) 2021 Elasticsearch BV" }
{"type": "server", "timestamp": "2025-06-12T17:16:22,238Z", "level": "INFO", "component": "o.e.x.s.a.s.FileRolesStore", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]" }
{"type": "server", "timestamp": "2025-06-12T17:16:22,627Z", "level": "INFO", "component": "o.e.i.g.ConfigDatabases", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "initialized default databases [[GeoLite2-Country.mmdb, GeoLite2-City.mmdb, GeoLite2-ASN.mmdb]], config databases [[]] and watching [/usr/share/elasticsearch/config/ingest-geoip] for changes" }
{"type": "server", "timestamp": "2025-06-12T17:16:22,628Z", "level": "INFO", "component": "o.e.i.g.DatabaseNodeService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "initialized database registry, using geoip-databases directory [/tmp/elasticsearch-8752342682551179973/geoip-databases/Ss5QwNv5QPWIXVibiBA-MA]" }
{"type": "server", "timestamp": "2025-06-12T17:16:22,948Z", "level": "INFO", "component": "o.e.t.NettyAllocator", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "creating NettyAllocator with the following configs: [name=elasticsearch_configured, chunk_size=1mb, suggested_max_allocation_size=1mb, factors={es.unsafe.use_netty_default_chunk_and_page_size=false, g1gc_enabled=true, g1gc_region_size=4mb}]" }
{"type": "server", "timestamp": "2025-06-12T17:16:22,988Z", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "using discovery type [zen] and seed hosts providers [settings]" }
{"type": "server", "timestamp": "2025-06-12T17:16:23,289Z", "level": "INFO", "component": "o.e.g.DanglingIndicesState", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually" }
{"type": "server", "timestamp": "2025-06-12T17:16:23,554Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "initialized" }
{"type": "server", "timestamp": "2025-06-12T17:16:23,554Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "starting ..." }
{"type": "server", "timestamp": "2025-06-12T17:16:23,560Z", "level": "INFO", "component": "o.e.x.s.c.f.PersistentCache", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "persistent cache index loaded" }
{"type": "server", "timestamp": "2025-06-12T17:16:23,560Z", "level": "INFO", "component": "o.e.x.d.l.DeprecationIndexingComponent", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "deprecation component started" }
{"type": "server", "timestamp": "2025-06-12T17:16:23,644Z", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}" }
{"type": "server", "timestamp": "2025-06-12T17:16:23,704Z", "level": "INFO", "component": "o.e.b.BootstrapChecks", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "bound or publishing to a non-loopback address, enforcing bootstrap checks" }

ERROR: [2] bootstrap checks failed. You must address the points described in the following [2] lines before starting Elasticsearch.
bootstrap check failure [1] of [2]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
bootstrap check failure [2] of [2]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/docker-cluster.log
{"type": "server", "timestamp": "2025-06-12T17:16:23,710Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "stopping ..." }
{"type": "server", "timestamp": "2025-06-12T17:16:23,724Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "stopped" }
{"type": "server", "timestamp": "2025-06-12T17:16:23,724Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "closing ..." }
{"type": "server", "timestamp": "2025-06-12T17:16:23,730Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "closed" }
{"type": "server", "timestamp": "2025-06-12T17:16:23,731Z", "level": "INFO", "component": "o.e.x.m.p.NativeController", "cluster.name": "docker-cluster", "node.name": "98f93dc53357", "message": "Native controller process has stopped - no new native processes can be started" }
```

</details>

But that at least sounds like it might be possible to proceed?

**Comment by linghengqian** [comment]
- This was indeed fixed by https://github.com/openjdk/jdk/pull/23811 , but the fix is only available in the unreleased OpenJDK 25. This actually destroys all Java containers?

- Given that most people use downstream distributions of OpenJDK, it's hard to say which distributions will backport this patch to older versions of JDK.

- Update in 2025.06.16: If I haven't misunderstood, this actually only affects containers that use JDK 17 to JDK 24.

**Comment by jandubois** [comment]
We will be releasing Rancher Desktop 1.19.2 which will downgrade the Linux kernel to avoid this issue for now. It is currently being tested and should be released in the next few days.

**Comment by jandubois** [comment]
Fixed in [Release Rancher Desktop 1.19.2](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.19.2)
